#!/bin/bash

<<comment

Need to create New User

comment


echo "========================This Script is Used to add New User ============================"

read -p "Please Provide YOur Username:" Username

sudo useradd -m "$Username"


echo "========================== $Username is created successfully ============================="


echo "========================= Set Password for user ======================================"


sudo passwd "$Username"

echo "======================= New Password sucessfully set for $Username ==========================="
